---
title: 错误处理
date: 2023-11-01
---



在传统开发模式中，我们使用try-catch语句来处理异步错误。如果你在async函数中使用try-catch，它可以捕获到await表达式中的错误。例如

``` javascript
// mapper.js
const db = require('./db');
async function getUser(id) {
    try {
        return await db.query('SELECT * FROM users WHERE id = ?', [id]);
    } catch (err) {
        console.error(err);
        throw new Error('Database query failed');
    }
}
module.exports = { getUser };
```
在这个示例中，我们使用try-catch语句来捕获数据库查询可能出现的错误。如果查询失败，我们会打印错误并抛出一个新的错误。

这样，即使数据库查询失败，也不会影响全局的错误处理。你可以在调用getUser函数的地方处理这个错误，例如在一个Express路由中：
``` javascript
router.get('/user/:id', async function (req, res, next) {
  try {
    const user = await getUser(req.params.id);
    res.send(user);
  } catch (err) {
    next(err);
  }
});
```

在这个示例中，如果getUser函数抛出一个错误，我们会调用next(err)将错误传递给下一个中间件，通常是一个错误处理中间件。这样，我们可以在一个统一的地方处理所有的错误。

::: tip 思考：

上面虽然解决了错误传递，防止全局服务崩溃，但是每一段代码都try catch这么写太麻烦了，能不能统一封装捕捉上述错误啊
:::




::: tip
在Node.js中，你可以使用一个库，如express-async-handler，来自动捕获异步错误并将它们传递给下一个中间件。这样，你就可以在一个统一的地方处理所有的错误。以下是一个使用express-async-handler的示例：
:::

``` javascript
const express = require('express');
const asyncHandler = require('express-async-handler');
const { getUser } = require('./mapper');
const router = express.Router();
router.get('/user/:id', asyncHandler(async function (req, res) {
  const user = await getUser(req.params.id);
  res.send(user);
}));
module.exports = router;

```

在这个示例中，我们使用asyncHandler包装了路由处理函数。如果getUser函数抛出一个错误，asyncHandler会自动捕获这个错误并调用next(err)将错误传递给下一个中间件。然后，你可以在你的应用中添加一个错误处理中间件来处理所有的错误：

``` javascript

app.use(function (err, req, res, next) {
  console.error(err.stack);
  res.status(500).send('Something broke!');
});

```
这样，你就可以在一个统一的地方处理所有的错误，而不需要在每个路由中都写try-catch。